# action.yml
name: 'Asana Github Action'
description: 'Creates an Asana Task when a PR is created'
inputs:
  ASANA_PROJECT_ID:
    description: 'Asana Project ID where the PR Tasks will be created'
    required: true
  PR_LINK:
    description: 'The PR to be reviewed'
    required: true
  GITHUB_TOKEN:
    description: 'Github Token to access the PR information'
    required: true
  ASANA_TOKEN:
    description: 'Asana Token to update the Asana Board with the created tasks'
    required: true
  USER_MAPPER:
    description: 'A json string with the mapping of github-username to asana-email-id'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ASANA_PROJECT_ID }}
    - ${{ inputs.PR_LINK }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.ASANA_TOKEN }}
    - ${{ inputs.USER_MAPPER }}